/**
 * Tailwind source inventory for the HTML shell generated by the WordPress
 * documentation publisher. Keep this list in sync with renderDocumentationPage.
 */
export const WORDPRESS_DOCUMENTATION_TAILWIND_CLASSES = `
-translate-x-1/2 -translate-y-1/2
[&_a]:font-semibold [&_a]:text-brand-600 [&_a]:underline-offset-4
[&_blockquote]:bg-brand-50/60 [&_blockquote]:border-brand-500
[&_blockquote]:border-l-4 [&_blockquote]:m-0 [&_blockquote]:px-5
[&_blockquote]:py-4 [&_blockquote]:rounded-r-2xl
[&_code]:bg-zinc-100 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded
[&_code]:text-sm [&_figure]:m-0
[&_h2]:border-b [&_h2]:border-zinc-200 [&_h2]:font-black [&_h2]:mb-0
[&_h2]:mt-8 [&_h2]:pb-3 [&_h2]:scroll-mt-28 [&_h2]:text-2xl
[&_h2]:text-zinc-950 [&_h2]:tracking-tight
[&_h3]:font-bold [&_h3]:mb-0 [&_h3]:mt-6 [&_h3]:scroll-mt-28
[&_h3]:text-xl [&_h3]:text-zinc-950
[&_li]:my-1 [&_ol]:m-0 [&_ol]:pl-6 [&_p]:m-0
[&_pre]:bg-zinc-950 [&_pre]:overflow-x-auto [&_pre]:p-5
[&_pre]:rounded-2xl [&_pre]:text-zinc-100
[&_pre_code]:bg-transparent [&_pre_code]:p-0
[&_strong]:text-zinc-950 [&_table]:border-collapse [&_table]:w-full
[&_td]:align-top [&_td]:border-b [&_td]:border-zinc-200 [&_td]:p-3
[&_th]:border-b [&_th]:border-zinc-300 [&_th]:p-3 [&_th]:text-left
[&_th]:text-zinc-950 [&_ul]:m-0 [&_ul]:pl-6
absolute bg-brand-50 bg-brand-500 bg-white bg-zinc-200 bg-zinc-300
bg-zinc-950 border border-b border-l border-zinc-200 bottom-2 bottom-3
cursor-pointer
dark:[&_a]:text-brand-400 dark:[&_blockquote]:bg-brand-950/20
dark:[&_code]:bg-zinc-800 dark:[&_h2]:border-zinc-800
dark:[&_h2]:text-white dark:[&_h3]:text-white
dark:[&_strong]:text-white dark:[&_td]:border-zinc-800
dark:[&_th]:border-zinc-700 dark:[&_th]:text-white
dark:bg-brand-950/40 dark:bg-white dark:bg-zinc-700 dark:bg-zinc-800
dark:bg-zinc-900 dark:border-zinc-800
dark:group-data-[active=true]:bg-brand-400
dark:group-data-[active=true]:ring-brand-950
dark:hover:bg-zinc-800/80 dark:hover:text-white dark:ring-brand-800
dark:ring-zinc-950 dark:text-brand-300 dark:text-brand-400 dark:text-white
dark:text-zinc-200
dark:text-zinc-300 dark:text-zinc-400 dark:text-zinc-950
fixed flex flex-col flex-nowrap font-black font-bold font-semibold
gap-0 gap-0.5 gap-1 gap-3 gap-4 gap-5 gap-8 grid group group/section
group-data-[active=true]:bg-brand-600
group-data-[active=true]:scale-125
group-data-[active=true]:ring-brand-100
group-focus-visible:bg-brand-500 group-focus-visible:opacity-100
group-hover:bg-brand-500 group-hover:opacity-100
group-open/section:rotate-180 group-open:rotate-180
h-1.5 h-2.5 h-4 h-7 h-8 hidden hover:[&_a]:underline hover:bg-zinc-100
hover:text-zinc-950 items-center items-start justify-between justify-center
justify-end leading-7 left-1/2 lg:basis-1/4 lg:basis-3/4 lg:block
lg:flex-nowrap lg:flex-row lg:hidden lg:pl-6 lg:pr-6 list-none m-0 marker:hidden ml-3
max-h-[70vh] max-h-[calc(100vh-7rem)] max-w-[1600px]
mb-10 mb-3 mb-6 min-w-0 mx-auto no-underline opacity-0 outline-none
overflow-y-auto p-0 p-3 pb-1 pb-2 pb-8 pl-3 pointer-events-none pr-0.5 pr-2
pt-1 pt-3 px-1 px-2 px-2.5 px-3 px-4 py-1 py-1.5 py-2 py-3
relative right-2 right-4 right-6 right-8
ring-1 ring-4 ring-brand-200 ring-inset ring-white rounded-2xl
rounded-full rounded-lg rounded-xl shadow-lg shadow-sm sm:text-4xl sticky
text-3xl text-base text-brand-600 text-brand-700 text-sm text-white text-xs
text-zinc-400 text-zinc-600 text-zinc-700 text-zinc-800 text-zinc-950
top-1/2 top-2 top-3
top-24 tracking-[0.18em] tracking-tight transition uppercase w-1.5 w-2.5
w-4 w-7 w-8 w-full w-px whitespace-nowrap xl:flex xl:pl-8 xl:pr-8 z-30
`;
